{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "f13b7753-96d8-4aad-8bda-bbf50317f8cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import keras\n",
    "from keras import layers, activations, ops\n",
    "import tensorflow as tf\n",
    "import os\n",
    "#tf.config.experimental.set_jit_compiler_enabled(False)\n",
    "#os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices=false'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "id": "d224f08a-1051-4241-930a-6f9708f0c60b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "x_train shape: (50000, 32, 32, 3) - y_train shape: (50000, 1)\n",
      "x_test shape: (10000, 32, 32, 3) - y_test shape: (10000, 1)\n"
     ]
    }
   ],
   "source": [
    "num_classes = 100\n",
    "input_shape = (32, 32, 3)\n",
    "\n",
    "(x_train, y_train), (x_test, y_test) = keras.datasets.cifar100.load_data()\n",
    "\n",
    "print(f\"x_train shape: {x_train.shape} - y_train shape: {y_train.shape}\")\n",
    "print(f\"x_test shape: {x_test.shape} - y_test shape: {y_test.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "id": "9a019033-c8d5-4e6f-929f-fd423c3024df",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Image size: 64 X 64 = 4096\n",
      "Patch size: 2 X 2 = 4 \n",
      "Patches per image: 1024\n",
      "Elements per patch (3 channels): 12\n",
      "Latent array shape: 256 X 256\n",
      "Data array shape: 1024 X 256\n"
     ]
    }
   ],
   "source": [
    "learning_rate = 0.001\n",
    "weight_decay = 0.0001\n",
    "batch_size = 5\n",
    "num_epochs = 2 # It is recommended to run 50 epochs to observe improvements in accuracy\n",
    "dropout_rate = 0.2\n",
    "image_size = 64  # We'll resize input images to this size.\n",
    "patch_size = 2  # Size of the patches to be extract from the input images.\n",
    "num_patches = (image_size // patch_size) ** 2  # Size of the data array.\n",
    "latent_dim = 256  # Size of the latent array.\n",
    "projection_dim = 256  # Embedding size of each element in the data and latent arrays.\n",
    "num_heads = 8  # Number of Transformer heads.\n",
    "ffn_units = [\n",
    "    projection_dim,\n",
    "    projection_dim,\n",
    "]  # Size of the Transformer Feedforward network.\n",
    "num_transformer_blocks = 4\n",
    "num_iterations = 2  # Repetitions of the cross-attention and Transformer modules.\n",
    "classifier_units = [\n",
    "    projection_dim,\n",
    "    num_classes,\n",
    "]  # Size of the Feedforward network of the final classifier.\n",
    "\n",
    "print(f\"Image size: {image_size} X {image_size} = {image_size ** 2}\")\n",
    "print(f\"Patch size: {patch_size} X {patch_size} = {patch_size ** 2} \")\n",
    "print(f\"Patches per image: {num_patches}\")\n",
    "print(f\"Elements per patch (3 channels): {(patch_size ** 2) * 3}\")\n",
    "print(f\"Latent array shape: {latent_dim} X {projection_dim}\")\n",
    "print(f\"Data array shape: {num_patches} X {projection_dim}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "347f46b5-b08d-4ee9-91ec-b675753995ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "data_augmentation = keras.Sequential(\n",
    "    [\n",
    "        layers.Normalization(),\n",
    "        layers.Resizing(image_size, image_size),\n",
    "        layers.RandomFlip(\"horizontal\"),\n",
    "        layers.RandomZoom(height_factor=0.2, width_factor=0.2),\n",
    "    ],\n",
    "    name=\"data_augmentation\",\n",
    ")\n",
    "# Compute the mean and the variance of the training data for normalization.\n",
    "data_augmentation.layers[0].adapt(x_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "e2d15449-776b-41c8-b322-bbcdb1b7f88f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_ffn(hidden_units, dropout_rate):\n",
    "    ffn_layers = []\n",
    "    for units in hidden_units[:-1]:\n",
    "        ffn_layers.append(layers.Dense(units, activation=activations.gelu))\n",
    "\n",
    "    ffn_layers.append(layers.Dense(units=hidden_units[-1]))\n",
    "    ffn_layers.append(layers.Dropout(dropout_rate))\n",
    "\n",
    "    ffn = keras.Sequential(ffn_layers)\n",
    "    return ffn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "2f4202c2-64b8-43e9-830c-3adaf34747cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_ffn(hidden_units, dropout_rate):\n",
    "    ffn_layers = []\n",
    "    for units in hidden_units[:-1]:\n",
    "        ffn_layers.append(layers.Dense(units, activation=activations.gelu))\n",
    "\n",
    "    ffn_layers.append(layers.Dense(units=hidden_units[-1]))\n",
    "    ffn_layers.append(layers.Dropout(dropout_rate))\n",
    "\n",
    "    ffn = keras.Sequential(ffn_layers)\n",
    "    return ffn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "31ed7b8e-5e07-401d-8dea-3160e2509329",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Patches(layers.Layer):\n",
    "    def __init__(self, patch_size):\n",
    "        super().__init__()\n",
    "        self.patch_size = patch_size\n",
    "\n",
    "    def call(self, images):\n",
    "        batch_size = ops.shape(images)[0]\n",
    "        patches = ops.image.extract_patches(\n",
    "            images=images,\n",
    "            size=(self.patch_size, self.patch_size),\n",
    "            strides=(self.patch_size, self.patch_size),\n",
    "            dilation_rate=1,\n",
    "            padding=\"valid\",\n",
    "        )\n",
    "        patch_dims = patches.shape[-1]\n",
    "        patches = ops.reshape(patches, [batch_size, -1, patch_dims])\n",
    "        return patches"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "77a66cd8-a2b8-4d69-af6e-59aae48dd966",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PatchEncoder(layers.Layer):\n",
    "    def __init__(self, num_patches, projection_dim):\n",
    "        super().__init__()\n",
    "        self.num_patches = num_patches\n",
    "        self.projection = layers.Dense(units=projection_dim)\n",
    "        self.position_embedding = layers.Embedding(\n",
    "            input_dim=num_patches, output_dim=projection_dim\n",
    "        )\n",
    "\n",
    "    def call(self, patches):\n",
    "        positions = ops.arange(start=0, stop=self.num_patches, step=1)\n",
    "        encoded = self.projection(patches) + self.position_embedding(positions)\n",
    "        return encoded"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "d33ca76a-3a26-4568-a422-fa5a7ddb6f8b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_cross_attention_module(\n",
    "    latent_dim, data_dim, projection_dim, ffn_units, dropout_rate\n",
    "):\n",
    "    inputs = {\n",
    "        # Recieve the latent array as an input of shape [1, latent_dim, projection_dim].\n",
    "        \"latent_array\": layers.Input(\n",
    "            shape=(latent_dim, projection_dim), name=\"latent_array\"\n",
    "        ),\n",
    "        # Recieve the data_array (encoded image) as an input of shape [batch_size, data_dim, projection_dim].\n",
    "        \"data_array\": layers.Input(shape=(data_dim, projection_dim), name=\"data_array\"),\n",
    "    }\n",
    "\n",
    "    # Apply layer norm to the inputs\n",
    "    latent_array = layers.LayerNormalization(epsilon=1e-6)(inputs[\"latent_array\"])\n",
    "    data_array = layers.LayerNormalization(epsilon=1e-6)(inputs[\"data_array\"])\n",
    "\n",
    "    # Create query tensor: [1, latent_dim, projection_dim].\n",
    "    query = layers.Dense(units=projection_dim)(latent_array)\n",
    "    # Create key tensor: [batch_size, data_dim, projection_dim].\n",
    "    key = layers.Dense(units=projection_dim)(data_array)\n",
    "    # Create value tensor: [batch_size, data_dim, projection_dim].\n",
    "    value = layers.Dense(units=projection_dim)(data_array)\n",
    "\n",
    "    # Generate cross-attention outputs: [batch_size, latent_dim, projection_dim].\n",
    "    attention_output = layers.Attention(use_scale=True, dropout=0.1)(\n",
    "        [query, key, value], return_attention_scores=False\n",
    "    )\n",
    "    # Skip connection 1.\n",
    "    attention_output = layers.Add()([attention_output, latent_array])\n",
    "\n",
    "    # Apply layer norm.\n",
    "    attention_output = layers.LayerNormalization(epsilon=1e-6)(attention_output)\n",
    "    # Apply Feedforward network.\n",
    "    ffn = create_ffn(hidden_units=ffn_units, dropout_rate=dropout_rate)\n",
    "    outputs = ffn(attention_output)\n",
    "    # Skip connection 2.\n",
    "    outputs = layers.Add()([outputs, attention_output])\n",
    "\n",
    "    # Create the Keras model.\n",
    "    model = keras.Model(inputs=inputs, outputs=outputs)\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "8428df34-8329-4d2a-8124-d44c2196ff0b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_transformer_module(\n",
    "    latent_dim,\n",
    "    projection_dim,\n",
    "    num_heads,\n",
    "    num_transformer_blocks,\n",
    "    ffn_units,\n",
    "    dropout_rate,\n",
    "):\n",
    "    # input_shape: [1, latent_dim, projection_dim]\n",
    "    inputs = layers.Input(shape=(latent_dim, projection_dim))\n",
    "\n",
    "    x0 = inputs\n",
    "    # Create multiple layers of the Transformer block.\n",
    "    for _ in range(num_transformer_blocks):\n",
    "        # Apply layer normalization 1.\n",
    "        x1 = layers.LayerNormalization(epsilon=1e-6)(x0)\n",
    "        # Create a multi-head self-attention layer.\n",
    "        attention_output = layers.MultiHeadAttention(\n",
    "            num_heads=num_heads, key_dim=projection_dim, dropout=0.1\n",
    "        )(x1, x1)\n",
    "        # Skip connection 1.\n",
    "        x2 = layers.Add()([attention_output, x0])\n",
    "        # Apply layer normalization 2.\n",
    "        x3 = layers.LayerNormalization(epsilon=1e-6)(x2)\n",
    "        # Apply Feedforward network.\n",
    "        ffn = create_ffn(hidden_units=ffn_units, dropout_rate=dropout_rate)\n",
    "        x3 = ffn(x3)\n",
    "        # Skip connection 2.\n",
    "        x0 = layers.Add()([x3, x2])\n",
    "\n",
    "    # Create the Keras model.\n",
    "    model = keras.Model(inputs=inputs, outputs=x0)\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "id": "b00cf766-4d71-4657-8d4f-c5f556392cc8",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Perceiver(keras.Model):\n",
    "    def __init__(\n",
    "        self,\n",
    "        patch_size,\n",
    "        data_dim,\n",
    "        latent_dim,\n",
    "        projection_dim,\n",
    "        num_heads,\n",
    "        num_transformer_blocks,\n",
    "        ffn_units,\n",
    "        dropout_rate,\n",
    "        num_iterations,\n",
    "        classifier_units,\n",
    "    ):\n",
    "        super().__init__()\n",
    "\n",
    "        self.latent_dim = latent_dim\n",
    "        self.data_dim = data_dim\n",
    "        self.patch_size = patch_size\n",
    "        self.projection_dim = projection_dim\n",
    "        self.num_heads = num_heads\n",
    "        self.num_transformer_blocks = num_transformer_blocks\n",
    "        self.ffn_units = ffn_units\n",
    "        self.dropout_rate = dropout_rate\n",
    "        self.num_iterations = num_iterations\n",
    "        self.classifier_units = classifier_units\n",
    "\n",
    "    def build(self, input_shape):\n",
    "        # Create latent array.\n",
    "        self.latent_array = self.add_weight(\n",
    "            shape=(self.latent_dim, self.projection_dim),\n",
    "            initializer=\"random_normal\",\n",
    "            trainable=True,\n",
    "        )\n",
    "\n",
    "        # Create patching module.\n",
    "        self.patcher = Patches(self.patch_size)\n",
    "\n",
    "        # Create patch encoder.\n",
    "        self.patch_encoder = PatchEncoder(self.data_dim, self.projection_dim)\n",
    "\n",
    "        # Create cross-attenion module.\n",
    "        self.cross_attention = create_cross_attention_module(\n",
    "            self.latent_dim,\n",
    "            self.data_dim,\n",
    "            self.projection_dim,\n",
    "            self.ffn_units,\n",
    "            self.dropout_rate,\n",
    "        )\n",
    "\n",
    "        # Create Transformer module.\n",
    "        self.transformer = create_transformer_module(\n",
    "            self.latent_dim,\n",
    "            self.projection_dim,\n",
    "            self.num_heads,\n",
    "            self.num_transformer_blocks,\n",
    "            self.ffn_units,\n",
    "            self.dropout_rate,\n",
    "        )\n",
    "\n",
    "        # Create global average pooling layer.\n",
    "        self.global_average_pooling = layers.GlobalAveragePooling1D()\n",
    "\n",
    "        # Create a classification head.\n",
    "        self.classification_head = create_ffn(\n",
    "            hidden_units=self.classifier_units, dropout_rate=self.dropout_rate\n",
    "        )\n",
    "\n",
    "        super().build(input_shape)\n",
    "\n",
    "    def call(self, inputs):\n",
    "        # Augment data.\n",
    "        augmented = data_augmentation(inputs)\n",
    "        # Create patches.\n",
    "        patches = self.patcher(augmented)\n",
    "        # Encode patches.\n",
    "        encoded_patches = self.patch_encoder(patches)\n",
    "        # Prepare cross-attention inputs.\n",
    "        cross_attention_inputs = {\n",
    "            \"latent_array\": ops.expand_dims(self.latent_array, 0),\n",
    "            \"data_array\": encoded_patches,\n",
    "        }\n",
    "        # Apply the cross-attention and the Transformer modules iteratively.\n",
    "        for _ in range(self.num_iterations):\n",
    "            # Apply cross-attention from the latent array to the data array.\n",
    "            latent_array = self.cross_attention(cross_attention_inputs)\n",
    "            # Apply self-attention Transformer to the latent array.\n",
    "            latent_array = self.transformer(latent_array)\n",
    "            # Set the latent array of the next iteration.\n",
    "            cross_attention_inputs[\"latent_array\"] = latent_array\n",
    "\n",
    "        # Apply global average pooling to generate a [batch_size, projection_dim] repesentation tensor.\n",
    "        representation = self.global_average_pooling(latent_array)\n",
    "        # Generate logits.\n",
    "        logits = self.classification_head(representation)\n",
    "        return logits"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "id": "e63a4201-3068-4402-85f2-33f07bae8a35",
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_experiment(model):\n",
    "    # Create ADAM instead of LAMB optimizer with weight decay. (LAMB isn't supported yet)\n",
    "    optimizer = keras.optimizers.Adam(learning_rate=learning_rate)\n",
    "\n",
    "    # Compile the model.\n",
    "    model.compile(\n",
    "        optimizer=optimizer,\n",
    "        loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),\n",
    "        metrics=[\n",
    "            keras.metrics.SparseCategoricalAccuracy(name=\"acc\"),\n",
    "            keras.metrics.SparseTopKCategoricalAccuracy(5, name=\"top5-acc\"),\n",
    "        ],\n",
    "    )\n",
    "\n",
    "    # Create a learning rate scheduler callback.\n",
    "    reduce_lr = keras.callbacks.ReduceLROnPlateau(\n",
    "        monitor=\"val_loss\", factor=0.2, patience=3\n",
    "    )\n",
    "\n",
    "    # Create an early stopping callback.\n",
    "    early_stopping = keras.callbacks.EarlyStopping(\n",
    "        monitor=\"val_loss\", patience=15, restore_best_weights=True\n",
    "    )\n",
    "\n",
    "    # Fit the model.\n",
    "    history = model.fit(\n",
    "        x=x_train,\n",
    "        y=y_train,\n",
    "        batch_size=batch_size,\n",
    "        epochs=num_epochs,\n",
    "        validation_split=0.1,\n",
    "        callbacks=[early_stopping, reduce_lr],\n",
    "    )\n",
    "\n",
    "    _, accuracy, top_5_accuracy = model.evaluate(x_test, y_test)\n",
    "    print(f\"Test accuracy: {round(accuracy * 100, 2)}%\")\n",
    "    print(f\"Test top 5 accuracy: {round(top_5_accuracy * 100, 2)}%\")\n",
    "\n",
    "    # Return history to plot learning curves.\n",
    "    return history"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "id": "41b8846a-d35c-41ac-aaf5-8661b370ec32",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-10-21 12:20:58.010836: W tensorflow/core/framework/op_kernel.cc:1855] OP_REQUIRES failed at xla_ops.cc:590 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference_one_step_on_data_137092[] on XLA_GPU_JIT: ImageProjectiveTransformV3 (No registered 'ImageProjectiveTransformV3' OpKernel for XLA_GPU_JIT devices compatible with node {{node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3}}){{node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3}}\n",
      "The op is created at: \n",
      "File \"usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
      "File \"usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "File \"usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n",
      "File \"usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n",
      "File \"usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 519, in dispatch_queue\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 508, in process_one\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 368, in execute_request\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 455, in do_execute\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 577, in run_cell\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\n",
      "File \"tmp/ipykernel_13395/1091006353.py\", line 15, in <module>\n",
      "File \"tmp/ipykernel_13395/2824899570.py\", line 26, in run_experiment\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 377, in fit\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 220, in function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\n",
      "File \"home"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3 defined at (most recent call last):\n<stack traces unavailable>\nDetected at node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3 defined at (most recent call last):\n<stack traces unavailable>\nDetected unsupported operations when trying to compile graph __inference_one_step_on_data_137092[] on XLA_GPU_JIT: ImageProjectiveTransformV3 (No registered 'ImageProjectiveTransformV3' OpKernel for XLA_GPU_JIT devices compatible with node {{node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3}}){{node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3}}\nThe op is created at: \nFile \"usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\nFile \"usr/lib/python3.10/runpy.py\", line 86, in _run_code\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 211, in start\nFile \"usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\nFile \"usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\nFile \"usr/lib/python3.10/asyncio/events.py\", line 80, in _run\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 519, in dispatch_queue\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 508, in process_one\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 368, in execute_request\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 455, in do_execute\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 577, in run_cell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\nFile \"tmp/ipykernel_13395/1091006353.py\", line 15, in <module>\nFile \"tmp/ipykernel_13395/2824899570.py\", line 26, in run_experiment\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 377, in fit\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 220, in function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 889, in _call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 696, in _initialize\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1060, in func_graph_from_py_func\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 339, in converted_call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 133, in multi_step_on_iterator\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 906, in _call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 132, in call_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1060, in func_graph_from_py_func\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 114, in one_step_on_data\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1673, in run\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3263, in call_for_each_replica\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 4061, in _call_for_each_replica\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 60, in train_step\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"tmp/ipykernel_13395/34977848.py\", line 73, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 220, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/functional.py\", line 183, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/function.py\", line 177, in _run_through_graph\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/functional.py\", line 648, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/tf_data_layer.py\", line 43, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/base_image_preprocessing_layer.py\", line 208, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/random_zoom.py\", line 179, in transform_images\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/random_zoom.py\", line 376, in _zoom_inputs\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/image.py\", line 361, in affine_transform\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py\", line 377, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/ops/gen_image_ops.py\", line 2592, in image_projective_transform_v3\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 614, in _create_op_internal\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 2726, in _create_op_internal\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1221, in from_node_def\n\ttf2xla conversion failed while converting __inference_one_step_on_data_137092[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n\t [[StatefulPartitionedCall]] [Op:__inference_multi_step_on_iterator_137678]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[95], line 15\u001b[0m\n\u001b[1;32m      1\u001b[0m perceiver_classifier \u001b[38;5;241m=\u001b[39m Perceiver(\n\u001b[1;32m      2\u001b[0m     patch_size,\n\u001b[1;32m      3\u001b[0m     num_patches,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     11\u001b[0m     classifier_units,\n\u001b[1;32m     12\u001b[0m )\n\u001b[0;32m---> 15\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mrun_experiment\u001b[49m\u001b[43m(\u001b[49m\u001b[43mperceiver_classifier\u001b[49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[94], line 26\u001b[0m, in \u001b[0;36mrun_experiment\u001b[0;34m(model)\u001b[0m\n\u001b[1;32m     21\u001b[0m early_stopping \u001b[38;5;241m=\u001b[39m keras\u001b[38;5;241m.\u001b[39mcallbacks\u001b[38;5;241m.\u001b[39mEarlyStopping(\n\u001b[1;32m     22\u001b[0m     monitor\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mval_loss\u001b[39m\u001b[38;5;124m\"\u001b[39m, patience\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m15\u001b[39m, restore_best_weights\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m     23\u001b[0m )\n\u001b[1;32m     25\u001b[0m \u001b[38;5;66;03m# Fit the model.\u001b[39;00m\n\u001b[0;32m---> 26\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     27\u001b[0m \u001b[43m    \u001b[49m\u001b[43mx\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mx_train\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     28\u001b[0m \u001b[43m    \u001b[49m\u001b[43my\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     29\u001b[0m \u001b[43m    \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbatch_size\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     30\u001b[0m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mnum_epochs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     31\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidation_split\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0.1\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m     32\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m[\u001b[49m\u001b[43mearly_stopping\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreduce_lr\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     33\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     35\u001b[0m _, accuracy, top_5_accuracy \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mevaluate(x_test, y_test)\n\u001b[1;32m     36\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTest accuracy: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mround\u001b[39m(accuracy\u001b[38;5;250m \u001b[39m\u001b[38;5;241m*\u001b[39m\u001b[38;5;250m \u001b[39m\u001b[38;5;241m100\u001b[39m,\u001b[38;5;250m \u001b[39m\u001b[38;5;241m2\u001b[39m)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3 defined at (most recent call last):\n<stack traces unavailable>\nDetected at node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3 defined at (most recent call last):\n<stack traces unavailable>\nDetected unsupported operations when trying to compile graph __inference_one_step_on_data_137092[] on XLA_GPU_JIT: ImageProjectiveTransformV3 (No registered 'ImageProjectiveTransformV3' OpKernel for XLA_GPU_JIT devices compatible with node {{node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3}}){{node perceiver_9_1/data_augmentation_1/random_zoom_3_1/ImageProjectiveTransformV3}}\nThe op is created at: \nFile \"usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\nFile \"usr/lib/python3.10/runpy.py\", line 86, in _run_code\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 211, in start\nFile \"usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\nFile \"usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\nFile \"usr/lib/python3.10/asyncio/events.py\", line 80, in _run\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 519, in dispatch_queue\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 508, in process_one\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 400, in dispatch_shell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 368, in execute_request\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 767, in execute_request\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 455, in do_execute\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 577, in run_cell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3077, in run_cell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3132, in _run_cell\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3336, in run_cell_async\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3519, in run_ast_nodes\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3579, in run_code\nFile \"tmp/ipykernel_13395/1091006353.py\", line 15, in <module>\nFile \"tmp/ipykernel_13395/2824899570.py\", line 26, in run_experiment\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 377, in fit\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 220, in function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 889, in _call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 696, in _initialize\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1060, in func_graph_from_py_func\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 339, in converted_call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 133, in multi_step_on_iterator\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 906, in _call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 132, in call_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1060, in func_graph_from_py_func\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 114, in one_step_on_data\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1673, in run\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3263, in call_for_each_replica\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 4061, in _call_for_each_replica\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 60, in train_step\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"tmp/ipykernel_13395/34977848.py\", line 73, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 220, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/functional.py\", line 183, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/function.py\", line 177, in _run_through_graph\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/functional.py\", line 648, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/tf_data_layer.py\", line 43, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/base_image_preprocessing_layer.py\", line 208, in call\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/random_zoom.py\", line 179, in transform_images\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/random_zoom.py\", line 376, in _zoom_inputs\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/image.py\", line 361, in affine_transform\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py\", line 377, in wrapper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/ops/gen_image_ops.py\", line 2592, in image_projective_transform_v3\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 614, in _create_op_internal\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 2726, in _create_op_internal\nFile \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1221, in from_node_def\n\ttf2xla conversion failed while converting __inference_one_step_on_data_137092[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n\t [[StatefulPartitionedCall]] [Op:__inference_multi_step_on_iterator_137678]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 889, in _call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 696, in _initialize\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1060, in func_graph_from_py_func\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 339, in converted_call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 133, in multi_step_on_iterator\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 906, in _call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 132, in call_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1060, in func_graph_from_py_func\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 114, in one_step_on_data\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1673, in run\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3263, in call_for_each_replica\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 4061, in _call_for_each_replica\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 60, in train_step\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"tmp/ipykernel_13395/34977848.py\", line 73, in call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 220, in call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/functional.py\", line 183, in call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/function.py\", line 177, in _run_through_graph\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/models/functional.py\", line 648, in call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/tf_data_layer.py\", line 43, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 936, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 58, in __call__\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/base_image_preprocessing_layer.py\", line 208, in call\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/random_zoom.py\", line 179, in transform_images\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/layers/preprocessing/image_preprocessing/random_zoom.py\", line 376, in _zoom_inputs\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/keras/src/backend/tensorflow/image.py\", line 361, in affine_transform\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py\", line 377, in wrapper\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/ops/gen_image_ops.py\", line 2592, in image_projective_transform_v3\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 614, in _create_op_internal\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 2726, in _create_op_internal\n",
      "File \"home/xy/Desktop/ml/keras/test/keras_test/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1221, in from_node_def\n",
      "\ttf2xla conversion failed while converting __inference_one_step_on_data_137092[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n"
     ]
    }
   ],
   "source": [
    "perceiver_classifier = Perceiver(\n",
    "    patch_size,\n",
    "    num_patches,\n",
    "    latent_dim,\n",
    "    projection_dim,\n",
    "    num_heads,\n",
    "    num_transformer_blocks,\n",
    "    ffn_units,\n",
    "    dropout_rate,\n",
    "    num_iterations,\n",
    "    classifier_units,\n",
    ")\n",
    "\n",
    "\n",
    "history = run_experiment(perceiver_classifier)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "edbbe238-fe8d-49be-b02c-b262fb57d3be",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43b503d8-5363-443b-8979-a09a6b4512c2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6db011b-1935-405a-be47-97faf298dfb2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1507c10-48ab-4da3-a46e-72392ce91468",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c374d4c-e07d-4277-aebc-bf72a30332a5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3a7fd8c6-3563-4127-97bb-bdda91d48a99",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9c09b04-f6af-4d02-b09b-8ed73457d1f9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "475f11dc-d64c-46d0-92cf-6fdc7654ce20",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f6a14bb4-0b4b-446e-bf4e-2298b0e72251",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9886e24f-9190-40e1-93ef-4b5991fce3e8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c5186cf2-1170-406a-802e-d9896b28f70d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4be50dca-afa2-4945-8fd7-879b70f26671",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d900029b-6dee-4e5b-9144-dee15d1ef00b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "95583462-d459-46f2-bcd3-e74d22a0aed0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
